import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Hanken_Grotesk, Poppins, Ubuntu } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

const hankenGrotesk = Hanken_Grotesk({
  subsets: ['latin'],
  variable: '--font-hanken-grotesk',
  weight: ['500', '700', '800'],
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  style: ['normal', 'italic'],
  weight: ['400', '700', '800'],
});

const ubuntu = Ubuntu({
  variable: '--font-ubuntu',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${hankenGrotesk.variable} ${ubuntu.variable} ${poppins.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
